### PR TITLE
Support shapes with textbox in if blocks

### LINKED ISSUE #26: Shapes with "<v:textbox/>" in "{{#if}}/{{/if}}" block are broken if no newline
Hi, I'm facing an issue with shapes (`<w:drawing/>`/`<a:graphic/>`) when used in conjunction with "if" blocks, e.g. :

image

The docx template: [shape-in-if.docx](https://github.com/jsreport/jsreport-docx/files/5820982/shape-in-if.docx)

When rendered, the following xmldom errors are produced:
```
[xmldom warning]        unclosed xml attribute
@#[line:1,col:163]
[xmldom warning]        unclosed xml attribute
@#[line:1,col:184]
[xmldom warning]        unclosed xml attribute
@#[line:1,col:210]
[xmldom warning]        unclosed xml attribute
@#[line:1,col:221]
[xmldom warning]        unclosed xml attribute
@#[line:1,col:422]
[xmldom warning]        unclosed xml attribute
@#[line:1,col:497]
[xmldom warning]        unclosed xml attribute
@#[line:1,col:584]
[xmldom warning]        unclosed xml attribute
@#[line:1,col:1133]
[xmldom warning]        unclosed xml attribute
@#[line:1,col:1143]
```

The generated output is then rejected by LibreOffice, Word 365 and xmllint:

```
-:2: namespace error : Namespace prefix a on graphicData is not defined
phicData uri="http://schemas.microsoft.com/office/word/2010/wordprocessingShape"
                                                                               ^
-:2: namespace error : Namespace prefix a on xfrm is not defined
d/2010/wordprocessingShape"/><wps:wsp/><wps:cNvSpPr/><wps:spPr><a:xfrm flipH="1"
                                                                               ^
-:2: namespace error : Namespace prefix a on off is not defined
ngShape"/><wps:wsp/><wps:cNvSpPr/><wps:spPr><a:xfrm flipH="1"><a:off x="0" y="0"
                                                                               ^
-:2: namespace error : Namespace prefix a on ext is not defined
><wps:spPr><a:xfrm flipH="1"><a:off x="0" y="0"/><a:ext cx="1534320" cy="219600"
                                                                               ^
-:2: namespace error : Namespace prefix a on prstGeom is not defined
0" y="0"/><a:ext cx="1534320" cy="219600"/></a:xfrm><a:prstGeom prst="homePlate"
                                                                               ^
-:2: namespace error : Namespace prefix a on avLst is not defined
><a:ext cx="1534320" cy="219600"/></a:xfrm><a:prstGeom prst="homePlate"><a:avLst
                                                                               ^
-:2: namespace error : Namespace prefix a on gd is not defined
</a:xfrm><a:prstGeom prst="homePlate"><a:avLst><a:gd name="adj" fmla="val 50000"
                                                                               ^
-:2: namespace error : Namespace prefix a on solidFill is not defined
><a:avLst><a:gd name="adj" fmla="val 50000"/></a:avLst></a:prstGeom><a:solidFill
                                                                               ^
-:2: namespace error : Namespace prefix a on srgbClr is not defined
j" fmla="val 50000"/></a:avLst></a:prstGeom><a:solidFill><a:srgbClr val="25b52c"
                                                                               ^
-:2: namespace error : Namespace prefix a on ln is not defined
Lst></a:prstGeom><a:solidFill><a:srgbClr val="25b52c"/></a:solidFill><a:ln w="0"
                                                                               ^
-:2: namespace error : Namespace prefix a on noFill is not defined
stGeom><a:solidFill><a:srgbClr val="25b52c"/></a:solidFill><a:ln w="0"><a:noFill
                                                                               ^
-:2: namespace error : Namespace prefix a on lnRef is not defined
a:solidFill><a:ln w="0"><a:noFill/></a:ln></wps:spPr><wps:style><a:lnRef idx="2"
                                                                               ^
-:2: namespace error : Namespace prefix a on schemeClr is not defined
><a:noFill/></a:ln></wps:spPr><wps:style><a:lnRef idx="2"><a:schemeClr val="dk1"
                                                                               ^
-:2: namespace error : Namespace prefix a on shade is not defined
wps:spPr><wps:style><a:lnRef idx="2"><a:schemeClr val="dk1"><a:shade val="50000"
                                                                               ^
-:2: namespace error : Namespace prefix a on fillRef is not defined
meClr val="dk1"><a:shade val="50000"/></a:schemeClr></a:lnRef><a:fillRef idx="1"
                                                                               ^
-:2: namespace error : Namespace prefix a on schemeClr is not defined
e val="50000"/></a:schemeClr></a:lnRef><a:fillRef idx="1"><a:schemeClr val="dk1"
                                                                               ^
-:2: namespace error : Namespace prefix a on effectRef is not defined
nRef><a:fillRef idx="1"><a:schemeClr val="dk1"/></a:fillRef><a:effectRef idx="0"
                                                                               ^
-:2: namespace error : Namespace prefix a on schemeClr is not defined
><a:schemeClr val="dk1"/></a:fillRef><a:effectRef idx="0"><a:schemeClr val="dk1"
                                                                               ^
-:2: namespace error : Namespace prefix a on fontRef is not defined
a:effectRef idx="0"><a:schemeClr val="dk1"/></a:effectRef><a:fontRef idx="minor"
                                                                               ^
-:2: parser error : Opening and ending tag mismatch: body line 2 and txbxContent
:sz w:val="24"/></w:rPr><w:t>value</w:t></w:r></w:p></w:r></w:p></w:txbxContent>
                                                                               ^
-:2: parser error : Opening and ending tag mismatch: document line 2 and txbx
24"/></w:rPr><w:t>value</w:t></w:r></w:p></w:r></w:p></w:txbxContent></wps:txbx>
                                                                               ^
-:2: parser error : Extra content at the end of the document
24"/></w:rPr><w:t>value</w:t></w:r></w:p></w:r></w:p></w:txbxContent></wps:txbx>
                                                                               ^
```

I'm trying to implement the following test case to demonstrate the issue but the xmldom parser is too lenient to pick up the XML errors:

```
  it('shape enclosed in if block', async () => {
    const result = await reporter.render({
      template: {
        engine: 'handlebars',
        recipe: 'docx',
        docx: {
          templateAsset: {
            content: fs.readFileSync(path.join(__dirname, 'shape-in-if.docx'))
          }
        }
      },
      data: {
        key: 'value'
      }
    })

    // Write document for easier debugging
    fs.writeFileSync('out.docx', result.content)

    const files = await decompress()(result.content)

    const doc = new DOMParser().parseFromString(
      files.find(f => f.path === 'word/document.xml').data.toString()
    )

    const generalTextElements = nodeListToArray(doc.getElementsByTagName('w:t'))

    generalTextElements.length.should.be.eql(2)
    should(generalTextElements[0].textContent).be.eql('value')
  })
})
```

Adding a newline right after `{{#if key}}` works around the issue, but it is not satisfying in my use case as it adds undesired line breaks in the output:

image

The difference with the broken output is this (ok left, ko right):

image

As you can see, some tags are closed too early in the broken output.

I believe I've narrowed down the issue a bit as commenting one of the two following calls eliminates the xmldom errors and produces correct ouput:
- either `concatTags()` in [`jsreport-docx/lib/preprocess/preprocess.js`](https://github.com/jsreport/jsreport-docx/blob/2.9.1/lib/preprocess/preprocess.js#L12)
- or `removeBlockHelper()` in [`jsreport-docx/lib/postprocess/postprocess.js`](https://github.com/jsreport/jsreport-docx/blob/2.9.1/lib/postprocess/postprocess.js#L17)

### PR DESCRIPTION
**Pull request by pdecat**
This PR intends to fix #26 by adding a comment right after closing `</w:p>` block helper tags to avoid matching nested `</w:p>` closing tags.

### CODE REVIEW

**Comment by pdecat** [comment]
This currently resolves the issue I reported in #26 but other tests are currently failing:

```
  97 passing (10s)
  8 failing

  1) docx
       list:
     AssertionError: expected 'This is title Some prefix: Jan And some postfix ' to contain 'Boris'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as containEql] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/test.js:569:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) docx
       list and links:
     AssertionError: expected 'jsreport ' to contain 'github'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as containEql] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/test.js:603:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) docx
       list nested:
     AssertionError: expected 'Boris item1 ' to contain 'Junior'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as containEql] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/test.js:716:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  4) docx
       table rows, columns (block):
     AssertionError: expected ' Name ' to contain 'Email'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as containEql] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/test.js:1135:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  5) docx
       table rows, columns (block and data index):
     AssertionError: expected ' 0-0 ' to contain '0-1'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as containEql] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/test.js:1168:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  6) docx
       table rows, columns (block and access to parent context):
     AssertionError: expected ' My Table - Name ' to contain 'My Table - Email'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as containEql] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/test.js:1202:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  7) docx
       text nodes with xml:space="preserve" should continue to exists when needed:
     AssertionError: expected ' My Table - Name ' to contain 'My Table - Email'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as containEql] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/test.js:4129:17)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  8) docx
       remove nodes that were just containing block helper definition calls:
     AssertionError: expected ' My Table - Name ' to contain 'My Table - Email'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as containEql] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/test.js:4179:17)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)



npm ERR! Test failed.  See above for more details.

```

**Comment by pdecat** [comment]
Adding the block helper comment inside the `<w:p/>` block helper tags ensures the comment is not moved around.

All tests are now passing:

```
npm test

> jsreport-docx@2.9.1 test /home/patrick/workspaces/js/jsreport/jsreport-docx
> mocha test --timeout 8000 && standard



  docx
    ✓ condition-with-helper-call (836ms)
    ✓ condition with docProps/thumbnail.jpeg in docx (109ms)
    ✓ variable-replace (88ms)
    ✓ variable-replace-multi (73ms)
    ✓ variable-replace-syntax-error
    ✓ invoice (169ms)
    ✓ endnote (79ms)
    ✓ footnote (59ms)
    ✓ link (57ms)
    ✓ link in header (149ms)
    ✓ link in footer (143ms)
    ✓ link in header, footer (149ms)
    ✓ link to bookmark should not break (133ms)
    ✓ watermark (58ms)
    ✓ list (62ms)
    ✓ list and links (76ms)
    ✓ list and endnotes (60ms)
    ✓ list and footnotes (68ms)
    ✓ list nested (74ms)
    ✓ variable-replace-and-list-after (51ms)
    ✓ variable-replace-and-list-after2 (79ms)
    ✓ variable-replace-and-list-after-syntax-error
    ✓ table (60ms)
    ✓ table and links (106ms)
    ✓ table and endnotes (89ms)
    ✓ table and footnotes (101ms)
    ✓ table nested (63ms)
    ✓ table vertical (58ms)
    ✓ table rows, columns (58ms)
    ✓ table rows, columns (block) (58ms)
    ✓ table rows, columns (block and data index) (58ms)
    ✓ table rows, columns (block and access to parent context) (56ms)
    ✓ style (47ms)
    ✓ image (51ms)
    ✓ image with placeholder size (usePlaceholderSize) (62ms)
    ✓ image with hyperlink inside (51ms)
    ✓ image error message when no src provided (42ms)
    ✓ image can render from url (52ms)
    ✓ image error message when src not valid param
    ✓ image error message when width not valid param (53ms)
    ✓ image error message when height not valid param
    ✓ image loop (59ms)
    ✓ image loop and hyperlink inside (56ms)
    ✓ image loop with bookmarks (138ms)
    ✓ loop (58ms)
    ✓ complex (687ms)
    ✓ input form control (70ms)
    ✓ checkbox form control (42ms)
    ✓ combobox form control (53ms)
    ✓ combobox form control with constant value (60ms)
    ✓ combobox form control with dynamic items (53ms)
    ✓ combobox form control with dynamic items in strings (55ms)
    ✓ combobox form control with dynamic items in strings and special character (51ms)
    ✓ chart (59ms)
    ✓ chart should allow adding more data series than the ones defined in template (67ms)
    ✓ chart should allow adding less data series than the ones defined in template (61ms)
    ✓ chart should allow producing chart with serie with empty values (63ms)
    ✓ chart should allow axis configuration for display (61ms)
    ✓ chart should allow axis configuration for min value (66ms)
    ✓ chart should allow axis configuration for max value (52ms)
    ✓ chart should allow axis configuration for min, max values (49ms)
    ✓ chart should allow axis configuration for stepSize value (49ms)
    ✓ chart should allow setting datalabels (52ms)
    ✓ chart without style, color xml files (52ms)
    ✓ chart with title (51ms)
    ✓ chart with dynamic title (51ms)
    ✓ scatter chart (47ms)
    ✓ bubble chart (48ms)
    ✓ stock chart (58ms)
    ✓ combo chart (chart that uses a different chart type per data serie) (67ms)
    ✓ waterfall chart (chartex) (64ms)
    ✓ funnel chart (chartex) (59ms)
    ✓ treemap chart (chartex) (74ms)
    ✓ sunburst chart (chartex) (89ms)
    ✓ clusteredColumn (chartex) (59ms)
    ✓ chart error message when no data (38ms)
    ✓ chart error message when no data.labels
    ✓ chart error message when no data.datasets
    ✓ chart loop (87ms)
    ✓ chart should keep style defined in serie (57ms)
    ✓ chart should keep number format defined in serie (57ms)
    ✓ should not duplicate drawing object id in loop (63ms)
    ✓ page break in single paragraph
    ✓ page break in single paragraph with condition (41ms)
    ✓ page break in single paragraph with condition #2
    ✓ page break in single paragraph (sharing text nodes)
    ✓ page break between paragraphs (41ms)
    ✓ should be able to reference stored asset (54ms)
    ✓ preview request should return html (132ms)
    ✓ text nodes with xml:space="preserve" should continue to exists when needed (63ms)
    ✓ remove nodes that were just containing block helper definition calls (70ms)
    ✓ raw
    ✓ raw error no parameter
    ✓ raw error no xml parameter
    ✓ raw error no replaceParentElement parameter
    ✓ raw error invalid replaceParentElement value
    ✓ raw error invalid wtc location
    ✓ shape with textbox enclosed in if block
    image size in cm
      ✓ image with custom size (width, height) (44ms)
      ✓ image with custom size (width set and height automatic - keep aspect ratio) (50ms)
      ✓ image with custom size (height set and width automatic - keep aspect ratio) (49ms)
    image size in px
      ✓ image with custom size (width, height) (45ms)
      ✓ image with custom size (width set and height automatic - keep aspect ratio) (45ms)
      ✓ image with custom size (height set and width automatic - keep aspect ratio) (47ms)

  docx with extensions.docx.previewInWordOnline === false
    ✓ preview request should not return html


  105 passing (11s)
```

**Comment by pdecat** [comment]
Note: the `<!--__block_helper_container__-->` are still left in the output document.xml right now, some cleanup is probably desired.

**Comment by bjrmatos** [comment]
thanks! fantastic work here, and a good idea about the comment node to make the match more precise

**Comment by bjrmatos** [comment]
i have added the cleanup for the comment nodes on master, just FYI. thanks again!

**Comment by pdecat** [comment]
Hi @bjrmatos, thanks!

I just thought this could be made even more robust by adding IDs to the block helpers to support them nested, e.g.:

```xml
<w:p __block_helper_container__="1">
  ...
  <w:p __block_helper_container__="2">
  ...
  <!--__block_helper_container__="2"--></w:p>
  ...
<!--__block_helper_container__="1"--></w:p>
```

That would require much more changes to the `recursiveStringReplaceAsync()` function to support back references in its `right` parameter from groups in its `left` parameter:

```js
  documentFile.data = await recursiveStringReplaceAsync(
    documentFile.data.toString(),
    '<w:p[^>]*__block_helper_container__="(\\d+)"[^>]*>',
    '<!--__block_helper_container__="\\1"--></w:p>',
    'g',
    async (val, content, hasNestedMatch) => {
    ...
    }
```

WDYT?

**Comment by bjrmatos** [comment]
yes, what you are describing sounds like the final solution for the strict matching, I will open a new issue to keep track of that, so we can find some time to work on it. but if you want to work on it the contribution is always welcome.

**Pull request merged**
